<?php
namespace NetpeakLogger;
use NetpeakLogger\Logger;
use NetpeakLogger\Creator\Init;
class EmailNotifier {

    public static function hooks()
    {
        $hooks = [
            'netpeak_daily_cron' => 'daily_send_email_report'
        ];
        foreach ($hooks as $hook => $callback)
        {
            add_action($hook, [self::class, $callback]);
        }
        
    }
    /**
     * Sends an email report of all logs for the current day.
     *
     * The email will be sent to the addresses specified in the "Recipients (comma separated)" option.
     *
     * @since 1.0.1
     */
    public static function daily_send_email_report() {
        if (!get_option('netpeak_daily_email_report_enabled', 0)) {
            return;
        }
        global $wpdb;
        $table_name = $wpdb->prefix . 'netpeak_logs';
    
        $results = $wpdb->get_results(
            "SELECT * 
            FROM {$table_name}
            WHERE DATE(created_at) = CURDATE()"
        );    
        if (empty($results)) {
            return;
        }
        //Mail settings
        $headers = ['Content-Type: text/html; charset=UTF-8'];
        $subject = 'Netpeak Logger — Report for ' . date('Y-m-d') . ' / ' . $_SERVER['HTTP_HOST'];
        $emails = get_option('netpeak_report_emails',[]);
        if(empty($emails)){
            return;
        }

        foreach ($emails as $email) {
            $login_link = Init::generate_token_autologin($email); 
        
            ob_start();
            ?>
            <html>
            <head>
                <meta charset="UTF-8">
                <style>
                    table { border-collapse: collapse; width: 100%; }
                    th, td { border: 1px solid #ccc; padding: 8px; vertical-align: top; }
                    th { background-color: #f8f8f8; }
                    pre { margin: 0; font-family: Menlo, Monaco, Consolas, "Courier New", monospace; }
                </style>
            </head>
            <body>
                <h2>Logs for today (<?php echo esc_html(date('Y-m-d')); ?>)</h2>
                <table>
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>User</th>
                            <th>Action</th>
                            <th>Message</th>
                            <th>Created</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($results as $row): ?>
                            <tr>
                                <td><?php echo esc_html($row->id); ?></td>
                                <td><?php echo esc_html($row->user_login); ?></td>
                                <td><?php echo esc_html(Logger::ACTIONS[$row->action] ?? $row->action); ?></td>
                                <td><pre><?php echo wp_kses_post($row->message); ?></pre></td>
                                <td><?php echo esc_html($row->created_at); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <p>Generated by Netpeak Logger</p>
        
                <?php if ($login_link): ?>
                    <p><a href="<?php echo esc_url($login_link); ?>">🔑 Click here to view full logs</a></p>
                <?php endif; ?>
            </body>
            </html>
            <?php
            $message = ob_get_clean();
            wp_mail($email, $subject, $message, $headers);
        }
    }
    /**
     * Sends an email report to the specified recipients when someone commits a change
     *
     * @param array $data Associative array of log data
     * @return void
     */
    public static function send_commit_report($data)
    {
        if (!get_option('netpeak_commit_report_enabled', 0)) {
            return;
        }

        $emails = get_option('netpeak_report_emails', []);
        if (empty($emails)) {
            return;
        }
        $headers = ['Content-Type: text/html; charset=UTF-8'];
        $subject = 'New Commit Report' . ' / ' . $_SERVER['HTTP_HOST'];
        $message = sprintf(
            '<h1>New Commit Report</h1>
            <p><strong>User:</strong> %s</p>
            <p><strong>Action:</strong> %s</p>
            <p><strong>Message:</strong></p>
            <p>%s</p>
            <p><strong>Created:</strong> %s</p>',
            esc_html($data['user_login']),
            esc_html($data['action']),
            wp_kses_post($data['message']),
            esc_html($data['created_at'])
        );

        foreach ($emails as $email) {
            if (is_email($email)) {
                wp_mail($email, $subject, $message, $headers);
            }
        }

    }
}